// Unit 1 完整数据(starter + unit 1-10)
const UNITS_DATA = {
  starter: {
    num: "Starter", name: "Starter", folder: "01 Starter",
    description: "家庭·学校·序数·月份",
    duration: "5:51", audio_file: "starter.mp3",
    pdf_start: 9, pdf_end: 15, book_start: 2, book_end: 8,
    topic_words: [
      {en:"family", zh:"家庭"}, {en:"school", zh:"学校"}, {en:"friend", zh:"朋友"},
      {en:"first", zh:"第一"}, {en:"January", zh:"一月"}, {en:"February", zh:"二月"},
      {en:"March", zh:"三月"}, {en:"April", zh:"四月"}, {en:"May", zh:"五月"},
      {en:"June", zh:"六月"}, {en:"July", zh:"七月"}, {en:"August", zh:"八月"},
      {en:"September", zh:"九月"}, {en:"October", zh:"十月"}, {en:"November", zh:"十一月"},
      {en:"December", zh:"十二月"},
    ],
    sections: ["topic_words", "fun_time", "sound", "talking"],
  },
  unit1: {
    num: "Unit 1", name: "Clubs in our school", folder: "02 Unit 1",
    description: "社团·摄影·艺术·园艺", big_task: "Making a photo diary of a club",
    duration: "5:35", audio_file: "unit_1.mp3",
    pdf_start: 16, pdf_end: 23, book_start: 9, book_end: 16,
    topic_words: [
      {en:"art", zh:"艺术"}, {en:"gardening", zh:"园艺"},
      {en:"storytelling", zh:"讲故事"}, {en:"take photos", zh:"拍照"},
    ],
    sound: "ph (photo)",
    sections: ["topic_words", "fun_time", "sound", "talking", "story"],
    story: {
      title: "At the Art Club",
      content: "Art Club 里 Miss Li 让大家画 brush pot。James 觉得难，Xiaopu 教他画竹子（Don't give up），最后 James 完成了 nice bamboo brush pot，领悟 easy-easier。",
      moral: "不放弃 + 互相帮助 + 熟能生巧",
    },
  },
  unit2: {
    num: "Unit 2", name: "Traditional games", folder: "03 Unit 2",
    description: "传统游戏·舞龙·长拳", big_task: "Talking about my favourite traditional game",
    duration: "5:21", audio_file: "unit_2.mp3",
    pdf_start: 24, pdf_end: 31, book_start: 17, book_end: 24,
    topic_words: [
      {en:"traditional", zh:"传统的"}, {en:"Chinese yo-yo", zh:"中国溜溜球"},
      {en:"kite-flying", zh:"放风筝"}, {en:"dragon dance", zh:"舞龙"}, {en:"tug of war", zh:"拔河"},
    ],
    sound: "ar (garden)",
    talking_pattern: "Look at me. I look/stand/sit like a...",
    sections: ["topic_words", "fun_time", "sound", "talking", "story"],
    story: {
      title: "The dragon dance",
      content: "Dragon Dance Club 为 garden party 训练，Minmin 跑太快导致队伍不协调，Mr Zhong 教 teamwork——按音乐节奏齐步走，长龙活起来。",
      moral: "团队协作 + 听从指挥",
    },
  },
  unit3: {
    num: "Unit 3", name: "Amazing plants", folder: "04 Unit 3",
    description: "植物·根茎叶·花朵", big_task: "Making a plant poster",
    duration: "5:51", audio_file: "unit_3.mp3",
    pdf_start: 32, pdf_end: 39, book_start: 25, book_end: 32,
    topic_words: [
      {en:"root", zh:"根"}, {en:"stem", zh:"茎"}, {en:"leaf", zh:"叶"},
      {en:"soil", zh:"土壤"}, {en:"water lily", zh:"睡莲"},
      {en:"pine cone", zh:"松果"}, {en:"morning glory", zh:"牵牛花"},
    ],
    sound: "ow (flower) / ou (out)",
    talking_pattern: "look(s) like...",
    sections: ["topic_words", "fun_time", "sound", "talking", "reading"],
    story: {
      title: "Plants and the weather",
      content: "四点钟花能预兆天气：早上合拢→晴天，6点后还开→多云/雨天。",
      moral: "观察自然现象",
    },
  },
  unit4: {
    num: "Unit 4", name: "Together with animals", folder: "05 Unit 4",
    description: "野生动物园·动物", big_task: "Writing a diary",
    duration: "6:02", audio_file: "unit_4.mp3",
    pdf_start: 40, pdf_end: 47, book_start: 33, book_end: 40,
    topic_words: [
      {en:"safari park", zh:"野生动物园"}, {en:"tiger", zh:"老虎"},
      {en:"lion", zh:"狮子"}, {en:"whale", zh:"鲸鱼"}, {en:"panda", zh:"熊猫"},
      {en:"giraffe", zh:"长颈鹿"}, {en:"hippo", zh:"河马"}, {en:"elephant", zh:"大象"},
    ],
    sound: "ear (wear) / ere (there) / air (hair)",
    talking_pattern: "feel/look/taste (adj.)...",
    sections: ["topic_words", "fun_time", "sound", "talking", "reading"],
    story: {
      title: "An animal keeper's diary",
      content: "动物管理员 Sangsang 记录熊猫幼崽：出生时粉色带白毛，眼睛睁不开但会爬，讲述熊猫成长过程。",
      moral: "关爱动物 + 观察自然",
    },
  },
  unit5: {
    num: "Unit 5", name: "Seeing a doctor", folder: "06 Unit 5",
    description: "看病·医生·华佗", big_task: "Giving health tips",
    duration: "6:16", audio_file: "unit_5.mp3",
    pdf_start: 48, pdf_end: 55, book_start: 41, book_end: 48,
    topic_words: [
      {en:"doctor", zh:"医生"}, {en:"cough", zh:"咳嗽"},
      {en:"runny nose", zh:"流鼻涕"}, {en:"nurse", zh:"护士"},
      {en:"fever", zh:"发烧"}, {en:"medicine", zh:"药"},
    ],
    sound: "c (medicine) / ce (nice) / ss (less)",
    talking_pattern: "Don't (do)...",
    sections: ["topic_words", "rhyme", "sound", "talking", "story"],
    story: {
      title: "The story of Hua Tuo",
      content: "华佗给病人治病：有人喊痛，华佗想如何减痛；另一人喝醉摔断腿，华佗用麻沸散让他睡着不感觉痛。",
      moral: "医者智慧 + 减轻病人痛苦",
    },
  },
  unit6: {
    num: "Unit 6", name: "Try my best", folder: "07 Unit 6",
    description: "努力·过去·未来", big_task: "Writing a letter to future me",
    duration: "5:33", audio_file: "unit_6.mp3",
    pdf_start: 56, pdf_end: 63, book_start: 49, book_end: 56,
    topic_words: [
      {en:"try my best", zh:"尽我所能"}, {en:"will", zh:"将"},
      {en:"succeed", zh:"成功"}, {en:"practice", zh:"练习"},
      {en:"better", zh:"更好"}, {en:"give up", zh:"放弃"},
    ],
    sound: "fr (front) / pr (practice) / tr (try)",
    talking_pattern: "was/were...",
    sections: ["topic_words", "fun_time", "sound", "talking", "story"],
    story: {
      title: "My left foot",
      content: "讲述者 4 个月大时生病只能动左脚，妈妈不放弃教他读写，问他「喜欢这个故事吗？点头/摇头」，最终成为现在的自己。",
      moral: "不放弃 + 妈妈的爱 + 意志力",
    },
  },
  unit7: {
    num: "Unit 7", name: "Great scientists", folder: "08 Unit 7",
    description: "伟大科学家·袁隆平", big_task: "Making a mini-book of great scientists",
    duration: "5:41", audio_file: "unit_7.mp3",
    pdf_start: 64, pdf_end: 71, book_start: 57, book_end: 64,
    topic_words: [
      {en:"scientist", zh:"科学家"}, {en:"explore", zh:"探索"},
      {en:"famous", zh:"著名的"}, {en:"discover", zh:"发现"},
      {en:"creative", zh:"有创造力的"}, {en:"hard-working", zh:"勤奋的"},
      {en:"(be) known as", zh:"被称为"},
    ],
    sound: "fl (fly) / pl (explore)",
    talking_pattern: "This is ..., a/the ...",
    sections: ["topic_words", "rhyme", "sound", "talking", "reading"],
    story: {
      title: "Great scientists",
      content: "袁隆平 1930 年生于北京，1960s 国家粮食短缺，他研究杂交水稻，creative & hard-working，养活很多人，被称「杂交水稻之父」。",
      moral: "科学贡献 + 创新 + 勤奋",
    },
  },
  unit8: {
    num: "Unit 8", name: "Useful inventions", folder: "09 Unit 8",
    description: "有用发明·轮子", big_task: "Making an ad for a useful invention",
    duration: "5:35", audio_file: "unit_8.mp3",
    pdf_start: 72, pdf_end: 79, book_start: 65, book_end: 72,
    topic_words: [
      {en:"useful", zh:"有用的"}, {en:"invention", zh:"发明"},
      {en:"problem", zh:"问题"}, {en:"wheel", zh:"轮子"},
      {en:"printing", zh:"印刷"}, {en:"television", zh:"电视"},
      {en:"light", zh:"灯"}, {en:"robot", zh:"机器人"},
    ],
    sound: "or (important)",
    talking_pattern: "It's important to (do)...",
    sections: ["topic_words", "fun_time", "sound", "talking", "reading"],
    story: {
      title: "The wheel moves on",
      content: "轮子有 5000+ 年历史，现在到处都有：家里、街边、教室，手表/钟/电扇/洗衣机里，自行车/汽车/火车/飞机上。",
      moral: "观察身边发明 + 致敬经典发明",
    },
  },
  unit9: {
    num: "Unit 9", name: "Using computers", folder: "10 Unit 9",
    description: "电脑·密码·Simon 答疑", big_task: "Making a quiz about computers",
    duration: "6:01", audio_file: "unit_9.mp3",
    pdf_start: 80, pdf_end: 87, book_start: 73, book_end: 80,
    topic_words: [
      {en:"laptop", zh:"笔记本电脑"}, {en:"password", zh:"密码"},
      {en:"mouse", zh:"鼠标"}, {en:"click", zh:"点击"},
      {en:"keyboard", zh:"键盘"}, {en:"email", zh:"电子邮件"},
      {en:"delete", zh:"删除"},
    ],
    sound: "ck (click)",
    talking_pattern: "as...as...",
    sections: ["topic_words", "fun_time", "sound", "talking", "reading"],
    story: {
      title: "Got a problem? Ask Simon!",
      content: "Star 88 写信给 Simon：爷爷送了新电脑，弟弟老开电脑删照片，Simon 建议设开机密码。",
      moral: "电脑使用常识 + 网络安全",
    },
  },
  unit10: {
    num: "Unit 10", name: "A greener life", folder: "11 Unit 10",
    description: "环保·减少·再利用", big_task: "Making a booklet on a greener life",
    duration: "6:14", audio_file: "unit_10.mp3",
    pdf_start: 88, pdf_end: 95, book_start: 81, book_end: 88,
    topic_words: [
      {en:"reduce", zh:"减少"}, {en:"reuse", zh:"再利用"},
      {en:"recycle", zh:"回收"}, {en:"throw away", zh:"扔掉"},
      {en:"turn off", zh:"关掉"}, {en:"pick up", zh:"捡起"},
    ],
    sound: "oy (boy)",
    talking_pattern: "It is a good way to (do)...",
    sections: ["topic_words", "song", "sound", "talking", "story"],
    story: {
      title: "Baggie's new life",
      content: "塑料袋 Baggie 被丢进海里，鲸鱼和海龟先后误食都吐出，Baggie 思考自己的新生活，呼吁减少塑料污染。",
      moral: "环保意识 + 减少塑料 + 保护海洋",
    },
  },
};
